---
title: "averaging AUC across folds"
---

```{r packages, message=FALSE, warning=FALSE}
library(tidyverse) ## load filter(), ... function
library(blockCV)
library(sf)
library(raster)
library(ggplot2)
library(shiny) ## what for ... ??
library(ROSE)
library(caret)
source("functions.R")
library(randomForest)
library(rpart.plot)
library(spdep)
library(rfPermute)
library(metRology)
library(caTools)
library(MASS)
```

To knit "by hand", `rmarkdown::render("Cross_validation.Rmd")`

```{r input_data}
## increase memory
if (.Platform$OS.type=="windows") memory.limit(1000000)

## get all data (as tables of x,y, predictors, change)
fn <- "rr_points14.RData"
if (!file.exists(fn)) {
    source("climate.R")
    source("winddir.R")
    source("basic.R")
}
load("rr_points14.RData")
## need
## R CMD BATCH --vanilla climate.R
## R CMD BATCH --vanilla winddir.R
## R CMD BATCH --vanilla basic.R

## test with smaller data set
datfun <- function(date, restrict_range=TRUE) {
    d1 <- rr_points14[[as.character(date)]]
    if (restrict_range) {
        d1 <- dplyr::filter(d1,
              x<604000 & y >284000 &  y < 2846000)
    }
    d1$change2 <- change_fun(d1$change)
    return(d1)
}
dat <- datfun(2014)
```

```{r upsample}
dat_gainfun <- function(x) dplyr::filter(dat, change2 %in% c("no gain", "gain")) 
dat_gain <- dat_gainfun(dat)
## analyzing gain only, first ...
if (file.exists("dat_upsample.rda")) {
    load("dat_upsample.rda")
}  else {
    set.seed(101)
    dat_upsample <- ROSE::ovun.sample(change ~ ., data = dat_gain, method = "both", N=1500)$data
    save(dat_upsample, file="dat_upsample.rda")
}
```

```{r classified_maps}
Classified1=raster("Classified1.tif")
Classified2=raster("classified2.tif")
```
The appropriate format of species data for the blockCV package is simple features (sf) or SpatialPointsDataFrame.pamake a SpatialPointsDataFrame object from data.frame
```{r numeric_data}
PA_data <- st_as_sf(dat_upsample, coords = c("x", "y"), crs = crs(Classified1))
```

```{r loop}
to_binary <- function(x) { as.numeric(x) -1 }
auc <- function(x) c(x$auc)
corners <- matrix(c(601500,605000,2839900,2835800,
                    601500,605000,2836000,2833500,
                    601500,605000,2843000,2839600,
                    601500,605000,2846500,2843000,
                    598500,601700,2843100,2839500,
                    598500,601500,2839500,2836000,
                    596000,598500,2846500,2842800,
                    595500,598500,2843500,2835000,
                    593500,595500,2846500,2843000),
                    ncol=4, byrow=TRUE,
                  dimnames=list(NULL,c("x1","x2","y1","y2")))

set.seed(101)
## set up empty vector for AUC values and an empty list for the
##  random forest fits
aucvec <- rep(NA,nrow(corners))
rflist <- list()                  
pts <- seq(nrow(dat_upsample))
for (i in seq(nrow(corners))) { ## set i = 1, 2, 3, ... number of squares (9)
    ## i <- 1
    cat(i,"\n")
    ## select test values in the square
    test <- pts[dat_upsample$x > corners[i,"x1"] &
                dat_upsample$x < corners[i,"x2"] &
                dat_upsample$y < corners[i,"y1"] &
                dat_upsample$y > corners[i,"y2"]]
    ## select train values as everything else
    train <- setdiff(pts,test)
    numFolds <- trainControl(method = "cv", number = 10) ## ???
    train2 <- PA_data[train,]
    test2  <- PA_data[test, ]
    train2$geometry <- NULL
    test2$geometry <- NULL
    ## fitting the random forest model,
    ##  saving the fitted model in rflist
    rflist[[i]] <- randomForest(formula= factor(change2) ~ . - landuse - change,
                        data = train2,
                        n.trees=400,interaction.depth=7,
                        ## do.trace=1,
                        type="classification", proximity=TRUE, trcontrol=numFolds, keep.inbag = TRUE)
    ## do the predictions, etc 
    predbc <- predict(rflist[[i]], newdata=test2, typeprobs="prob", predict.all=TRUE)
    ff2 <-  factor(test2$change,
                   ## 0 = no gain,  1 = gain
                   levels=c(0,1),  ## these are the values in the original vector
                   labels=c("no gain","gain") ## these will be the names in the new vector
                   )
    table(ff2)
    ## try() doesn't stop if there's an error
    rocCurve2 <- try(pROC::roc(to_binary(ff2),
                               to_binary(predbc$aggregate)))
    ## calculate auc (if the test data had gain and no gain) and store it in the vector
    if (!inherits(rocCurve2, "try-error")) {
        aucvec[i] <- auc(rocCurve2)
    }
}
```

```{r print_aucvec}
print(aucvec)
```

Out of bag (OOB) score is a way of validating the Random forest model.

```{r Out_of_Bag_error, eval=FALSE}
get_err <- function(x) {
    err <- x$err.rate
    tail(err[,"OOB"],1)
}
## get the OOB error for every fold
oobvec <- sapply(rflist,get_err)
```
for all data

```{r loop2}
date <- c(1987,1997,2003,2008,2014)
## extract a separate data frame for each date
datall <- map(date, ~datfun(.)) ## '.' means "each dataset in turn"
names(datall) <- date
## select only 'no gain'/'gain' pixels (i.e. pixels that started as NOT erg)
dat_gainall <- map(datall, ~dat_gainfun(dat))
names(dat_gainall) <- date
## we can't use map() here (because ROSE::ovun.sample() tries to do something clever
## that breaks it), so we have to set up our own list, compute each value, and add it
## to the list
dat_upsampleall <- list()  ## create an empty list
for (i in seq_along(dat_gainall)) {  ## seq_along -> {1,2,3,4,5}
    ## compute upsampled data for the next data set and put it in the list
    dat_upsampleall[[i]] <-
        ROSE::ovun.sample(change ~ .,  ## this '.' means "all variables other than 'change'"
                          data = dat_gainall[[i]], 
                          method = "both", N=1500)$data
}
## make sure that results are named by year ...
names(dat_upsampleall) <- date
```

```{r check_upsamples}
sapply(dat_upsampleall,nrow)
```

## next step ...
